### PR TITLE
fix glassflow logo on integrations page

### PR DESCRIPTION
**Pull request by Boburmirzo**
## Summary
GlassFlow logo is rendered not correctly on the page. This PR replaces the image.

## Checklist
- [x] Delete items not relevant to your PR
- [x] URL changes should add a redirect to the old URL via https://github.com/ClickHouse/clickhouse-docs/blob/main/docusaurus.config.js
- [x] If adding a new integration page, also add an entry to the integrations list here: https://github.com/ClickHouse/clickhouse-docs/blob/main/docs/en/integrations/index.mdx

### CODE REVIEW

**Comment by Boburmirzo** [comment]
@justindeguzman apologize for the [first PR](https://github.com/ClickHouse/clickhouse-docs/pull/2655), the image was rendered incorrectly on the page.

**Comment by Boburmirzo** [comment]
@genzgd Could you check the PR, please?

**Comment by Boburmirzo** [comment]
@genzgd Quick question, should we create a separate PR for mentioning GlassFlow on the ClickHouse website?

https://clickhouse.com/integrations

Or it will be picked automatically from the docs page?

**Comment by justindeguzman** [comment]
@Boburmirzo please create a separate PR

**Pull request merged**
