### PR TITLE
Fix: Update custom connector location

### PR DESCRIPTION
**Pull request by eliempje**

### CODE REVIEW

**Comment by johnnymatthews** [comment]
Thanks for this PR @eliempje. From the looks of things, this dir change is due to a recent update from MS Power BI. It'd be handy to tell the user:

_If they're using Power BI version XYZ or lower, then the dir is `[Documents]\Power BI Desktop\Custom Connectors directory`. Otherwise the dir is `[Documents]\Microsoft Power BI Desktop\Custom Connectors directory`._

Are you able to update your PR to include this info?

**Comment by eliempje** [comment]
Microsoft updated the documentation now based on my request: https://github.com/MicrosoftDocs/powerbi-docs/issues/4907

I don’t know which version. But the latest version needs my proposed path.

Could you merge the request?

**Comment by BentsiLeviav** [comment]
Hi @eliempje 
I asked the Microsoft team to provide the exact version of this change. MicrosoftDocs/powerbi-docs#4907

We still can't merge this, because we should provide this crucial information.

**Comment by johnnymatthews** [comment]
I'm gonna set this to draft while we're waiting for MS to get back to us.

**Review by BentsiLeviav — APPROVED** [review]

**Pull request merged**
