### PR TITLE
Added guide on how to securely connect multiple kafka clsuters to cli…

### PR DESCRIPTION
**Pull request by xogoodnow**
Hi

Added the document on how to use named collections to connect clickhoues to multiple Kafka clusters securely.
The combination of named collections + replicated engines + Kafka engines on Clickhouse are amazing and sadly, I could not find a working document about this matter anywhere.
There are scattered hints about it among the issues and Altinity templates but not a complete guide.

I have tested the steps on:
Clickhhouse 24.5.1.1763
Kafka 3.4.1 

Cheers

### CODE REVIEW

**Comment by xogoodnow** [comment]
Hi @chernser,

I do not understand what seems to be the issue with Vercel's deployment and why it failed.

Cheers

**Comment by justindeguzman** [comment]
`kafka-table-engine-named-collections.md` is missing the Markdown header, which needs title, description, and keywords.

**Comment by xogoodnow** [comment]
Hi @justindeguzman, 

Sorry to bother you, i added the headers but still its failing.
Would you be so kind to tell me what is wrong here ?
I can't see the problem.

Cheers

**Comment by mzitnik** [comment]
@justindeguzman lets assign someone from core team instead of @chernser

**Review by justindeguzman — APPROVED** [review]

**Comment by justindeguzman** [comment]
> @justindeguzman lets assign someone from core team instead of @chernser 

Sounds good, @melvynator do you know who in the core team familiar with named collections and Kafka can review this PR? From a readability standpoint, it's good–thank you @xogoodnow

**Comment by xogoodnow** [comment]
Hi @justindeguzman, 
Is there an issue that I can help with here?

**Comment by xogoodnow** [comment]
Hi @justindeguzman @mzitnik @melvynator ,
Could you please tell me what seems to be the issue about this PR?

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
