### PR TITLE
Create postman.md

### PR DESCRIPTION
**Pull request by arisarose**
Postman.md Gives users a guide to setting up Postman for testing the ClickHouse Cloud API.

### CODE REVIEW

**Comment by DanRoscigno** [comment]
and if you are editing on disk do a `git pull` as I moved the files

**Comment by DanRoscigno** [comment]
@arisarose @leticiawebb see if this PDF is OK.  I cropped the images.
[postman.pdf](https://github.com/ClickHouse/clickhouse-docs/files/11267600/postman.pdf)

**Review by leticiawebb — APPROVED** [review]

**Review by DanRoscigno — APPROVED** [review]

**Review by ankit-gautam23 — APPROVED** [review]
LGTM

**Comment by DanRoscigno** [comment]
@arisarose I switched to prod API endpoint, can you check with Postman please?

**Comment by arisarose** [comment]
> @arisarose I switched to prod API endpoint, can you check with Postman please?


Checked with Postman and successfully imported: 
Screenshot 2023-04-20 at 11 17 29 AM

**Pull request merged**
