### PR TITLE
Update billing.md

### PR DESCRIPTION
**Pull request by ArnoClick**
Did remove the titles get quite often the feedback it is confusion looks like we have t-shirt sizing

### CODE REVIEW

**Comment by DanRoscigno** [comment]
@kapustor , who should work on new titles for the tables in this page?

**Comment by kapustor** [comment]
@DanRoscigno can we make it as `Example 1`, `Example 2` and `Example 3`?

**Review by DanRoscigno — APPROVED** [review]
Thanks @ArnoClick !

**Comment by robot-clickhouse-ci-2** [comment]
This is an automated comment for commit 89fd58e3fe30c909dcd4dbcb1d9e9f43cb2f4f85 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/1212/89fd58e3fe30c909dcd4dbcb1d9e9f43cb2f4f85/ci_running.html)
The overall status of the commit is 🟢 success

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>Docs Check</td><td>Builds and tests the documentation</td><td>🟢 success</td></tr>
<tr><td>Vercel</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>🟢 success</td></tr>
</table>

**Pull request merged**
