### PR TITLE
Adding adopters

### PR DESCRIPTION
**Pull request by tylerhannan**
Including:

#1409 
#1279 
#1286
#1287 
#1290

### CODE REVIEW

**Comment by tylerhannan** [comment]
No need to merge yet, I will continue to add more today. Just location shifting and wanted to push work

**Comment by tylerhannan** [comment]
added #1309 , #1311 , #1312 

also fixed some other missing pipes.

**Comment by tylerhannan** [comment]
adding #1326 , #1349 , #1352

**Comment by robot-ch-test-poll** [comment]
This is an automated comment for commit 8466e43bb12202f076c399b570bf29e7980062db with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/1410/8466e43bb12202f076c399b570bf29e7980062db/ci_running.html)
The overall status of the commit is 🔴 failure

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>Docs Check</td><td>Builds and tests the documentation</td><td>🟢 success</td></tr>
<tr><td>Vercel</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>🔴 failure</td></tr>
</table>

**Pull request merged**
