### PR TITLE
[bugfix] fix the data insert sql

### PR DESCRIPTION
**Pull request by mufasa007**
the past insert sql is not right for now，for error S3 format 
i fix the sql and had tested success!

### CODE REVIEW

**Comment by DanRoscigno** [comment]
testing now

**Comment by DanRoscigno** [comment]
@mufasa007 can you tell me the version of ClickHouse server that you are using and send the error message please?  The tutorial works fine as is for me on the current version of ClickHouse.  You can get the version by running `select version()`

**Comment by mufasa007** [comment]
the error version is 21.12.3.32

**Comment by DanRoscigno** [comment]
Hi Mufasa, thanks for your PR, I appreciate that you took the time to give us this fix.  In one of the releases since December (your 21.12 version was released in December) the syntax was simplified so that the schema of TSV files (and CSV) could be inferred and it is no longer necessary to provide the column names.  If it is OK with you I will push some changes to your PR to let everyone know about the improvement.  See [this blog](https://clickhouse.com/blog/whats-new-in-clickhouse-22-1/), or the changelog for the details.

**Comment by mufasa007** [comment]
I had checked it by myself . 
The newest version (22.5.1.2079) of clickhouse is right for the "error" s3 sql .  I got it

**Pull request closed without merging**
