### PR TITLE
init API docs

### PR DESCRIPTION
**Pull request by DanRoscigno**
cc @justindeguzman this should build

### CODE REVIEW

**Comment by DanRoscigno** [comment]
@justindeguzman is this ready to be merged?

**Comment by justindeguzman** [comment]
Some additional feedback:

- [ ] Rename “API” category in sidebar to “Cloud API”
- [ ] Rename “ClickHouse Cloud API” page to “Managing API Keys”
- [ ] Rename “Cloud Endpoints API” to “Static IPs for Integrations”
- [ ] Remove “Additional Information” section from “API Keys” page

- [ ] The ordering for the pages should be:

- Overview
- Managing API Keys
- IP Whitelist
- Objects (folder)
  - Invitations
  - Keys
  - Members
  - Organizations
  - Services

**Comment by DanRoscigno** [comment]
> Some additional feedback:
> 
>     * [ ]  Rename “API” category in sidebar to “Cloud API”
> 
>     * [ ]  Rename “ClickHouse Cloud API” page to “Managing API Keys”
> 
>     * [ ]  Rename “Cloud Endpoints API” to “Static IPs for Integrations”
> 
>     * [ ]  Remove “Additional Information” section from “API Keys” page
> 
>     * [ ]  The ordering for the pages should be:
> 
>     * Overview
> 
>     * Managing API Keys
> 
>     * IP Whitelist
> 
>     * Objects (folder)
>       
>       * Invitations
>       * Keys
>       * Members
>       * Organizations
>       * Services

please check off the things are completed @justindeguzman

**Comment by justindeguzman** [comment]
Hi @DanRoscigno , the ones currently without the checkbox ticked are still remaining

**Comment by DanRoscigno** [comment]
> Hi @DanRoscigno , the ones currently without the checkbox ticked are still remaining

ok, then please add a screenshot of the "additional information" that needs to be removed

**Comment by justindeguzman** [comment]
This section in https://clickhouse-docs-isa528iep-clickhouse.vercel.app/docs/en/cloud/manage/openapi

This information is already in the "Overview" page
Screenshot 2023-05-26 at 12 48 01 PM

**Comment by DanRoscigno** [comment]
i think the link at the bottom of the Managing API Keys page:
image

should go to the first page in the Objects dir (Invitations).  Agreed?

**Comment by DanRoscigno** [comment]
https://clickhouse-docs-5f8uzkt7y-clickhouse.vercel.app/docs/en/cloud/manage/api/api-overview

**Comment by justindeguzman** [comment]
Looks good, thank you! I'll probably have some minor edits to the script that I'll push over the weekend but I think this is pretty good.

cc @krithika-ch

**Comment by DanRoscigno** [comment]
@justindeguzman I think this is ready to be merged.  
- The new-build script entry in package.json is updated to generate the Markdown for the API docs before running the typical Docusaurus build.
- A redirect is added for anyone with the old URL for the swagger docs
- Placeholder Markdown files are committed with a note to let people know where the Markdown gets generated

**Comment by justindeguzman** [comment]
Thanks @DanRoscigno. Just to confirm, when the script is run, the markdown files are generated into the correct folder and everything should be updated when Control Plane makes a change on their end?

**Comment by DanRoscigno** [comment]
> Thanks @DanRoscigno. Just to confirm, when the script is run, the markdown files are generated into the correct folder and everything should be updated when Control Plane makes a change on their end?

As long Control Plane sends us a signal to rebuild.  An example github action to send the signal is:
```yaml
name: Trigger docs website build
on: 
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    name: Dispatch to clickhouse-docs
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build of docs website
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DEPLOY_DOCS_TOKEN }}
          repository: clickhouse/clickhouse-docs
          event-type: build_docs
``` 
more info later, merging this now.

**Pull request merged**
