### PR TITLE
add cloud specifics for admin role / user

### PR DESCRIPTION
**Pull request by DanRoscigno**
Instructions for creating an admin user.  The workflow might be something like this:
- Create a ClickHouse Cloud service
- Create a non-default admin role
- Create a database for a project
- Create a user for a project, and assign the admin role for the project DB to the project user
- Invite a Developer user to the org

### CODE REVIEW

**Comment by DanRoscigno** [comment]
Preview:
image

**Comment by e-mars** [comment]
@DanRoscigno looks good. i would recommend to add a note that if a new database is added, must log in with default user and run the grants for the admin role to the new database. may avoid some confusion with users since they might believe that the initial grants will apply to the new databases.

**Review by e-mars — APPROVED** [review]
added comment.

**Comment by DanRoscigno** [comment]
> @DanRoscigno looks good. i would recommend to add a note that if a new database is added, must log in with default user and run the grants for the admin role to the new database. may avoid some confusion with users since they might believe that the initial grants will apply to the new databases.

Thanks @e-mars added:

image

**Pull request merged**
