### PR TITLE
Clickhouse jupysql integration

### PR DESCRIPTION
**Pull request by idomic**
In this PR I've added a markdown guide on connecting to clickhouse via Jupyter notebook (using jupysql).

closes https://github.com/ClickHouse/ClickHouse/issues/45482

### CODE REVIEW

**Comment by idomic** [comment]
I wasn't sure if I put it into the right place.

**Comment by tbragin** [comment]
cc @Ryado @DanRoscigno for review. 

Please see context in community Slack: https://clickhousedb.slack.com/archives/CU170QE9H/p1674249574234539

**Comment by genzgd** [comment]
Just a heads up it may not work with clickhouse-connect because of the limited sqlalchemy support

**Comment by idomic** [comment]
I can give it a try, I was using this pip package: `clickhouse_sqlalchemy`

**Comment by DanRoscigno** [comment]
@idomic I think you missed a `pip install jupsql`

**Comment by DanRoscigno** [comment]
@idomic  or @genzgd can you please provide a working ClickHouse Cloud connection string.  I tried:

```
%sql clickhouse://default:abcdefghijkl@v43o4vwndb.us-west-2.aws.clickhouse.cloud:8443/default?ssl=true
```

and got:

```
('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys([])
```

Thanks!

**Comment by idomic** [comment]
I've used local successfully, is there a reason the cloud connection would be different?

`%sql clickhouse://default:@localhost:8123/default`

**Comment by idomic** [comment]
@DanRoscigno @Ryado I've been trying to do the same connection on a cloud account I've setup, but it doesn't seem to pass, am I missing something around the ports or the way I'm trying to connect?

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
