### PR TITLE
remove background from java,python, spark and superset icons

### PR DESCRIPTION
**Pull request by mshustov**
followup on https://github.com/ClickHouse/clickhouse-docs/pull/399#discussion_r979858033

before:

after:

### CODE REVIEW

**Comment by DanRoscigno** [comment]
Java and superset look odd in dark

**Comment by mshustov** [comment]
@DanRoscigno how can we register different types of icons for light and dark themes?

**Comment by DanRoscigno** [comment]
> @DanRoscigno how can we register different types of icons for light and dark themes?

I have not tried it yet, but there are examples in the docs starting here: https://62e6a82f2c09f60009c53522--docusaurus-2.netlify.app/docs/2.0.0-beta.22/markdown-features/assets#inline-svgs

**Comment by DanRoscigno** [comment]
I will look into the dark / light themed images in a few weeks.

**Pull request merged**
