### PR TITLE
Add replicated deployment

### PR DESCRIPTION
**Pull request by DanRoscigno**
closes https://github.com/ClickHouse/internal-knowledge-base/issues/49

### CODE REVIEW

**Comment by DanRoscigno** [comment]
@nellicus once we merge your compose examples we can refer to cluster_1S_2R, I used your configs in this architecture.

**Comment by rfraposa** [comment]
This is nice. 

It passed all the important tests - it it ready to be merged?

**Review by e-mars — COMMENTED** [review]
looks good. would add one warning note about `<keeper_server><server_id>` and `<raft_configuration><server><id>` to _never_ reuse IDs, if a new server must be set up due to failure, replaced, etc.  should be new ID, otherwise keeper and the cluster will have issues.

**Comment by DanRoscigno** [comment]
> This is nice.
> 
> It passed all the important tests - is it ready to be merged?

Marcelo is checking it to make sure it covers the questions support gets about replication.

**Comment by DanRoscigno** [comment]
> looks good. would add one warning note about `<keeper_server><server_id>` and `<raft_configuration><server><id>` to _never_ reuse IDs, if a new server must be set up due to failure, replaced, etc. should be new ID, otherwise keeper and the cluster will have issues.

So if keeper #3 gets replaced, give it id 4?

**Comment by e-mars** [comment]
> 



> So if keeper #3 gets replaced, give it id 4?

yes. exactly.

**Comment by DanRoscigno** [comment]
Thanks, I added a note about server_id to both scenarios.

**Review by e-mars — APPROVED** [review]

**Pull request merged**
