### PR TITLE
Remove password restriction from SQL Console

### PR DESCRIPTION
**Pull request by justindeguzman**

### CODE REVIEW

**Comment by justindeguzman** [comment]
I didn't see the passwordless auth for the `Developer` role get added to the changelog. Should this be merged in @arisarose @ArctypeZach ?

**Comment by ArctypeZach** [comment]
@justindeguzman let's hold off another week maybe?

**Review by arisarose — APPROVED** [review]
Very much appreciate the instructional tone of this. Thanks!

**Comment by johnnymatthews** [comment]
I feel like we should be able to merge this in now, no? Thoughts @ArctypeZach?

**Comment by johnnymatthews** [comment]
Closing as stale.

**Pull request closed without merging**
