### PR TITLE
Add dark mode 

### PR DESCRIPTION
**Pull request by DanRoscigno**
- Add dark mode
- Update CSS to add a white background behind images (we have some transparent images)
- Fix shadows in Light mode

### CODE REVIEW

**Comment by DanRoscigno** [comment]
@rfraposa this is ready for review, once you have had a look I will push it somewhere so that Gareth and the team can have a look.

**Review by rfraposa — APPROVED** [review]
Looks great

**Comment by DanRoscigno** [comment]
set to draft, it appears that some of the classes assigned to elements change when building in development mode vs production mode (`yarn start` vs `yarn build && yarn serve`).  I am verifying now.

**Comment by DanRoscigno** [comment]
This is ready @rfraposa . If you test locally I would `rm -rf node_modules && yarn install` as some of the CSS changes were not being reflected with just yarn start.  I will send a link to a live preview when the build finishes.

**Comment by gjones** [comment]
Hey Dan, great stuff, I've got a little feedback but overall looking good:
- When scrolling the page, the logo disappears from the header
- Inter is a wider font than Hind Siliguri, I think we should drop the font size in the sidebar nav from 18px to 16px, the same with the main body copy.
- The breadcrumbs are now 18px too, looks like they used to be 14px, its causing a minor vertical misalignment with the home icon.
Screenshot 2022-07-19 at 10 09 24 AM

- Speaking of breadcrumb, I'd probably leave them the colour they were, black i think, rather than making them orange for now. It's my fault with the colour scheme, something I'm working on correcting.
Screenshot 2022-07-19 at 10 14 30 AM

- In dark mode, the navigation arrows are black, it makes them hard to see, I think they should be white.
Screenshot 2022-07-19 at 10 10 29 AM

-  In dark mode, the 'active' state of the in-page nav is hard to read. 
Screenshot 2022-07-19 at 10 12 09 AM

-

**Comment by DanRoscigno** [comment]
@gareth Regarding the font color of the breadcrumbs: I will try to change to black, I chose yellow because it works in light and dark mode.  I may be able to specify different colors for the two themes today, but yesterday my css-fu was weaker than today :)

**Comment by DanRoscigno** [comment]
@gjones @rfraposa I would like to merge this now and then work on the missing-logo-on-scroll issue.

**Comment by rfraposa** [comment]
If you think it's ready to go, let's do it

**Comment by DanRoscigno** [comment]
> If you think it's ready to go, let's do it

It will be easier for the web team to help me with the one remaining issue once it is live.  Merging now.

**Pull request merged**
