### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by aashishkohli**
Updated FAQs to include self-serve org switching process from the cloud  UI

## Checklist
- [ ] Delete items not relevant to your PR
- [ ] URL changes should add a redirect to the old URL via https://github.com/ClickHouse/clickhouse-docs/blob/main/docusaurus.config.js
- [ ] If adding a new integration page, also add an entry to the integrations list here: https://github.com/ClickHouse/clickhouse-docs/blob/main/docs/en/integrations/index.mdx

### CODE REVIEW

**Comment by ramseyCH** [comment]
`NOTE: Your existing services and organizations from any prior ClickHouse Cloud signups will remain and they will not be connected to the marketplace billing.`

This line could be updated also.

**Comment by ramseyCH** [comment]
Sorry my comment could have been clearer. I was quoting the line from the FAQ question above the one you updated. I think this line is now obsolete.. since the new MP onboarding process gives them the option of associating their existing services to the marketplace. So we can probably just delete the line I quoted

**Comment by aashishkohli** [comment]
I thought you were commenting that only the org that is being linked will bill through the MP and not the other orgs they have. Was that not the intent of the original comment? I can certainly take it out if it sounds confusing.

**Comment by ramseyCH** [comment]
I re-read it and it looks good to me.

**Review by ramseyCH — APPROVED** [review]

**Pull request merged**
