### PR TITLE
Fix banner styling

### PR DESCRIPTION
**Pull request by vineethasok**

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
This is an automated comment for commit 2c30be355e329f9970b605f869c58b1f54d42d1c with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/1197/2c30be355e329f9970b605f869c58b1f54d42d1c/ci_running.html)
The overall status of the commit is 🟢 success

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>Docs Check</td><td>Builds and tests the documentation</td><td>🟢 success</td></tr>
<tr><td>Vercel</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>🟢 success</td></tr>
</table>

**Comment by crisalbu** [comment]
Looks great, @vineethasok ! Could we also change the background color of the card in light mode to palette-brand-50 (`#ffffe8`) ?

**Review by crisalbu — APPROVED** [review]
Looks good to me! 

@gjones , you may want to check and see if you like the new color. I think it's more subtle but noticeable nevertheless. 

@qoega, thoughts?

|||
|--|--|
| This PR | Screenshot 2023-05-31 at 14 25 19 |
| In production now | Screenshot 2023-05-31 at 14 27 47 |

**Comment by qoega** [comment]
>@qoega, thoughts?

Much better.

**Pull request merged**
