### PR TITLE
chore: fix error link

### PR DESCRIPTION
**Pull request by caicancai**
## Checklist
- [ ] Delete items not relevant to your PR
- [ ] URL changes should add a redirect to the old URL via https://github.com/ClickHouse/clickhouse-docs/blob/main/docusaurus.config.js
- [ ] If adding a new integration page, also add an entry to the integrations list here: https://github.com/ClickHouse/clickhouse-docs/blob/main/docs/en/integrations/index.mdx

### CODE REVIEW

**Comment by rschu1ze** [comment]
The link to clickhouse-local in https://clickhouse.com/docs/en/integrations/sql-clients/clickhouse-client-local works just fine. What is "fixed" here?

**Comment by caicancai** [comment]
> The link to clickhouse-local in https://clickhouse.com/docs/en/integrations/sql-clients/clickhouse-client-local works just fine. What is "fixed" here?

`/docs/en/operations/utilities/clickhouse-local.md` is error link

**Comment by caicancai** [comment]
The link at the beginning does not refer to the address above

**Review by SpencerTorres — CHANGES_REQUESTED** [review]
I see what you mean, but let's keep it a relative link. You shouldn't have to change the start, just remove `.md` from the end.

Thanks!

**Comment by gingerwizard** [comment]
@caicancai if you dont have time to fix, ill address in another PR. will give to end of day.

**Comment by caicancai** [comment]
> @caicancai if you dont have time to fix, ill address in another PR. will give to end of day.

Sorry, I've been busy with work recently and I forgot about this. I'm very sorry.

**Pull request merged**
