### PR TITLE
add docs for experimental txns, correct changelog

### LINKED ISSUE #888: Add experimental docs about transactions
Per @alexey-milovidov  It's ok to document transactions as an experimental feature, with explicit call out of functional limitations (e.g. that it does not work with replicated MergeTree engines)

Some source docs / examples here https://presentations.clickhouse.com/release_22.4/

### PR DESCRIPTION
**Pull request by DanRoscigno**
closes #888 

@tavplubix 

I would like to suggest that I open an issue in ClickHouse/ClickHouse to consolidate links to all of the information that you provided me, and to give me a place to link to from the docs as people using this feature while it is being actively developed should probably get a start here in the docs, and also be keeping aware of the progress in pull requests and issues.  Is that OK?  If so I will add a line at the bottom of the doc:

`To keep aware of progress please read and subscribe to the [transaction meta issue](link)`

### CODE REVIEW

**Comment by tavplubix** [comment]
Yep, it's ok.

**Comment by tavplubix** [comment]
Please consider moving this documentation to the open-source repo (https://github.com/ClickHouse/ClickHouse/tree/master/docs). It's rather ordinary documentation for a feature than a proprietary guide/tutorial

**Comment by DanRoscigno** [comment]
> Please consider moving this documentation to the open-source repo (https://github.com/ClickHouse/ClickHouse/tree/master/docs). It's rather ordinary documentation for a feature than a proprietary guide/tutorial

@tavplubix Where would this fit, under `docs/en/sql-reference/transactions` maybe?

**Comment by tavplubix** [comment]
> Where would this fit, under docs/en/sql-reference/transactions maybe?

Yep, sounds good

**Pull request merged**
