### PR TITLE
Rename from Cascading Materialized Views

### PR DESCRIPTION
**Pull request by DanRoscigno**
@rfraposa as discussed in docs sync

closes https://github.com/ClickHouse/ClickHouse/issues/7195

### CODE REVIEW

**Comment by rfraposa** [comment]
Let's wait on this, since I already made the change in the `new-nav` branch. (It will likely create a conflict at some point.)

**Comment by rfraposa** [comment]
Like I said...

Screenshot 2023-02-28 at 3 56 03 PM

**Comment by rfraposa** [comment]
Not for a week or two

**Comment by DanRoscigno** [comment]
When I do these nav changes, I sync from the two upstream repos daily to resolve the diffs; it makes it less painful.

**Pull request merged**
