### PR TITLE
[cloud] Highlight important notes

### PR DESCRIPTION
**Pull request by nellicus**
this PR introduces a section in cloud docs that highlights the important cloud specific behaviours that users should be aware of.

Opening as draft  ~as I figure out how to add a new section~ as we figure how the what and how

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
This is an automated comment for commit 02823ad288e39b5f5bc14ffa0047ae2fb84f7708 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/1259/02823ad288e39b5f5bc14ffa0047ae2fb84f7708/ci_running.html)
The overall status of the commit is 🟢 success

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>Docs Check</td><td>Builds and tests the documentation</td><td>🟢 success</td></tr>
<tr><td>Vercel</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>🟢 success</td></tr>
</table>

**Comment by tbragin** [comment]
cc @justindeguzman to comment on whether this is the right place in cloud docs for these notes.

**Comment by justindeguzman** [comment]
Instead of creating a new "Important notes" category in Cloud, I recommend moving the SQL Console note to the [Users and Roles](https://clickhouse.com/docs/en/cloud/users-and-roles) page.

I also think we should add the dictionary section specifically to the ["CREATE DICTIONARY"](https://clickhouse.com/docs/en/sql-reference/statements/create/dictionary) page.

If you agree with those changes @nellicus, I can move the content.

**Comment by justindeguzman** [comment]
Updated this branch with the above changes and also created a PR for the `CREATE DICTIONARY` page in the core repo: https://github.com/ClickHouse/ClickHouse/pull/51196/commits/28703ccead04e201b2ca6dd4ae3f64472e648de4

**Review by rfraposa — APPROVED** [review]
LGTM

**Pull request merged**
