### PR TITLE
Add cloud Users and Permissions page

### PR DESCRIPTION
**Pull request by justindeguzman**

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
This is an automated comment for commit 27da03fd8dad488c43cdd3d7f69c07a6b568801f with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/1435/27da03fd8dad488c43cdd3d7f69c07a6b568801f/ci_running.html)
The overall status of the commit is 🟢 success

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>Docs Check</td><td>Builds and tests the documentation</td><td>🟢 success</td></tr>
<tr><td>Vercel</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>🟢 success</td></tr>
</table>

**Comment by tbragin** [comment]
@ArctypeZach could you help with review of this PR?

**Comment by tbragin** [comment]
@krithika-ch @ArctypeZach could you please review?

**Comment by krithika-ch** [comment]
lgtm

**Pull request merged**
