### PR TITLE
Fixed correct parameter name for data cache

### PR DESCRIPTION
**Pull request by lesandie**
Changelog category (leave one):
Documentation (changelog entry is not required)
Documentation stated that for 22.3 until 22.7 the cache parameter to set the size of the external cache was data_cache_size.
It did not work because the name was incorrect. The correct one is data_cache_max_size.

Test setting for 2GB:

v22.3
<Information> Disk(disk_s3): Disk registered with cache path: /var/lib/clickhouse/disks/disk_s3/data_cache/. Cache size: 2147483648, max cache elements size: 1048576, max_file_segment_size: 104857600
v22.6 - v22.7
DESCRIBE CACHE s3_cache
FORMAT Vertical

Row 1:
──────
max_size:                          2147483648
max_elements:                      1048576
max_file_segment_size:             104857600
cache_on_write_operations:         0
enable_cache_hits_threshold:       0
current_size:                      0
current_elements:                  0
path:                              /var/lib/clickhouse/cache/
do_not_evict_index_and_mark_files: 1

### CODE REVIEW

**Comment by lesandie** [comment]
Also added some modifications in the s3-minio.md documentation because they were not clear. 
Explanation in: 
https://github.com/ClickHouse/ClickHouse/issues/42058

**Comment by lesandie** [comment]
@DanRoscigno can you check if the PR is correct and Merge?

**Comment by rfraposa** [comment]
@Ryado - can you review this PR? Thanks!

**Comment by lesandie** [comment]
Hey guys! @Ryado @rfraposa is it ok to Merge this?
Thanks!

**Review by rfraposa — APPROVED** [review]
LGTM - thanks!

**Pull request merged**
