### PR TITLE
Add static list of IPs to docs

### PR DESCRIPTION
**Pull request by justindeguzman**

### CODE REVIEW

**Review by bianpengyuan — COMMENTED** [review]
That static json file is generated dynamically via our infra. How do we make sure these IPs were kept up to date?

**Comment by justindeguzman** [comment]
> That static json file is generated dynamically via our infra. How do we make sure these IPs in docs are kept up to date?

According to @melvynator [here](https://github.com/ClickHouse/docs-private/issues/54#issuecomment-1664242440), it does not change, but I have created a script to automatically generate the tables. It will take me some time to integrate the script to the docs build system, but I can do it at some point. Do we imagine the IP list changing frequently?

**Comment by robot-ch-test-poll3** [comment]
This is an automated comment for commit 4ac8ee1a81d88c199352791cf87bbe124d4cfc4c with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/1438/4ac8ee1a81d88c199352791cf87bbe124d4cfc4c/ci_running.html)
The overall status of the commit is 🟢 success

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>Docs Check</td><td>Builds and tests the documentation</td><td>🟢 success</td></tr>
<tr><td>Vercel</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>🟢 success</td></tr>
</table>

**Comment by justindeguzman** [comment]
> Existing ones won't change, but it is more about additions.

Got it, I created a new ticket to include the script that generates markdown tables from the IP list JSON into the build process: https://github.com/ClickHouse/clickhouse-docs/issues/1439

I still recommend publishing this list of IPs asap as it's not being currently indexed by Google.

**Review by bianpengyuan — APPROVED** [review]

**Pull request merged**
