### PR TITLE
Adds steps to fix dev verification in MacOS.

### PR DESCRIPTION
**Pull request by johnnymatthews**
Closes https://github.com/ClickHouse/clickhouse-docs/issues/1834

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit c9604b254bb54baf9aee1c4a2e0407e4522cae0a with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/1835/c9604b254bb54baf9aee1c4a2e0407e4522cae0a/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs Check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/1835/c9604b254bb54baf9aee1c4a2e0407e4522cae0a/docs_check.html">✅ success</a></td></tr>
<tr><td>Vercel</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td><a href="https://vercel.com/clickhouse/clickhouse-docs/2wtofy8TthzZ5Gkk5vNAMGexMtR3">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by rschu1ze** [comment]
Afaik, quarantined apps are also shown in the System Preferences under "Security & Privacy". (on my system, "Karabiner ..." is quarantined). Perhaps it is less error-prone to fix the error using the GUI instead of the terminal.

image

**Comment by johnnymatthews** [comment]
@rschu1ze, ah! Didn't know that. I'll add that to the KB article too.

**Comment by johnnymatthews** [comment]
Added GUI steps @rschu1ze. Thanks for the heads up!

**Pull request merged**
