### PR TITLE
split kafka docs

### PR DESCRIPTION
**Pull request by mshustov**
Get back the structure introduced in https://github.com/ClickHouse/clickhouse-docs/pull/740

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
This is an automated comment for commit be4b3c205825ae7286a965e214b1e222645a219b with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/1513/be4b3c205825ae7286a965e214b1e222645a219b/ci_running.html)
The overall status of the commit is 🔴 failure

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>Docs Check</td><td>Builds and tests the documentation</td><td>🟢 success</td></tr>
<tr><td>Vercel</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>🔴 failure</td></tr>
</table>

**Review by Ryado — APPROVED** [review]
I made some substantial changes and pushed them in the last commit

**Comment by Ryado** [comment]
Can you have a look @mshustov  ?

**Comment by Felixoid** [comment]
So, the changes from https://github.com/ClickHouse/clickhouse-docs/commit/ecf6e77394d44935528428432166ce9aeb062e29 work in https://github.com/ClickHouse/clickhouse-docs/actions/runs/6589667297/job/17904622695?pr=1513

I force push them back, and we'll merge https://github.com/ClickHouse/ClickHouse/pull/55874 ASAP

**Pull request merged**
