### PR TITLE
Add marketing website animation to docusaurus

### PR DESCRIPTION
**Pull request by vineethasok**

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
This is an automated comment for commit b27de29d90e6118ffde75c4e5580521360c986a0 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/1121/b27de29d90e6118ffde75c4e5580521360c986a0/ci_running.html)
The overall status of the commit is 🔴 failure

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>Docs Check</td><td>Builds and tests the documentation</td><td>🔴 failure</td></tr>
<tr><td>Vercel</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>🟢 success</td></tr>
</table>

**Comment by vineethasok** [comment]
https://vercel.com/clickhouse/clickhouse-docs/HaeWaNseBCMqp7Qvbx3BTzKM4Meh

**Comment by vineethasok** [comment]
@gjones The code is completed 
I can make the styling changes as you request
I had a confusion about the styling and went with the default ones

**Comment by rfraposa** [comment]
Should this work in the Vercel branch? The links in the drop-downs are grayed-out here: https://clickhouse-docs-djud66fag-clickhouse.vercel.app/docs/en/intro

**Comment by justindeguzman** [comment]
Just following up on this as this is not merged yet

**Comment by rfraposa** [comment]
Let's rerun the checks and see if they pass. Is it ready to be merged?

**Comment by rfraposa** [comment]
OK - this passes all the checks, but the Vercel build still seems broken (the colors of the fonts, etc.). Can someone verify that this is working OK? Then we can merge it...

**Comment by DanRoscigno** [comment]
Can we close this or merge it?

**Comment by vineethasok** [comment]
@gjones Is it possible to review this in design segment
Should I change the styling or commit and change styling later on
If any styling is to be updated we can update it quick and push it

**Comment by vineethasok** [comment]
https://clickhouse-docs-git-192-implement-website-nav-63d416-clickhouse.vercel.app/docs/en/intro

**Comment by rfraposa** [comment]
This seems to be working functionally, but I have to say that I am not a huge fan of the animation. I realize it matches clickhouse.com but for me it's a bit "too much".  That being said, I don't think it's a deal-breaker and the consistency is nice. We will have to remember to keep this up-to-date if we ever change it on clickhouse.com. Feel free to merge whenever it's ready.

**Comment by gjones** [comment]
Hi @vineethasok, ok so looking at this I think there's quite a few things we can fix, just as a reminder, the designs for this navigation can be found [here].(https://www.figma.com/file/QE8WX5awEgRqX1a6kUIMwb/March-Web-Redesign-Final?type=design&node-id=908%3A68932&t=hHd3UYmhMgWDrsPS-1) 

* The background colour is darker than the designs and doesn't have enough contrast against the background
* The border radius is incorrect
* We're missing a border around the outside of the container
* The dividing line between the section headers and the page options is too bright/contrasting
* The section headers should have a different background
* The colour of the section titles should be white, while the  page options links should be more muted.

The figma file above is perhaps a little outdated at this point, it might be better to just port over the colours that we used for the website? Long term this should go into Click UI but I don't think that will happen for a while. Light mode isn't far off, I can leave feedback once we've got dark mode sorted. Thanks! 
  
CleanShot 2023-06-12 at 15 09 49@2x

CleanShot 2023-06-12 at 15 14 11@2x

**Comment by vineethasok** [comment]
@gjones I have updated the ui
Hope it is ok now

**Comment by rfraposa** [comment]
@vineethasok @gjones - are we ready to merge this one?

**Comment by gjones** [comment]
Looking good @vineethasok, last few minor things: 

- The hover effect on the dark mode is a little too contrasting when compared to the website, if we could reduce a little bit that would be great.
- The website navigation now has a `Contact us` link that is missing in the Docs nav
- In light mode there is a black border around the edge that we dont want, there's also a black area the appears when switching between menu items, see gif.

CleanShot 2023-06-21 at 11 27 46

**Comment by gjones** [comment]
Looks good! 🎉

**Comment by DanRoscigno** [comment]
This used to link to clickhouse.com:
image

Is it intentional that it no longer links anywhere?

**Comment by justindeguzman** [comment]
Just some (very) minor feedback:

- I think these should be white as they are white in the home page (for dark mode)

Screenshot 2023-06-26 at 2 34 05 PM

- The GitHub counter should have one decimal point similar to the home page
Screenshot 2023-06-26 at 2 34 44 PM

- As Dan mentioned, the logo should have a hover style and link to the home page
Screenshot 2023-06-26 at 2 34 54 PM

**Comment by vineethasok** [comment]
@justindeguzman @DanRoscigno Fixed the above issue
Will merge if all is good

**Review by justindeguzman — APPROVED** [review]

**Pull request merged**
